<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Karthick" failures="1" tests="4" name="Workflow Test" time="47.606" errors="0" timestamp="2024-08-12T21:49:03 IST">
  <testcase classname="tests.LoginPageTest" name="loginTest" time="8.516"/>
  <testcase classname="tests.SignupPageTest" name="signupTest" time="6.634"/>
  <testcase classname="tests.ProductBuyTest" name="addProductTest" time="13.086"/>
  <testcase classname="tests.CartFailureTest" name="testCartIconAfterRemovingProduct" time="11.004">
    <failure type="java.lang.AssertionError" message="Cart icon should display 0 after removing the product expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: Cart icon should display 0 after removing the product expected [0] but found [1]
at tests.CartFailureTest.testCartIconAfterRemovingProduct(CartFailureTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCartIconAfterRemovingProduct -->
</testsuite> <!-- Workflow Test -->
